"""Added required tables

Revision ID: 56cc58aa691c
Revises: 6d5a126f64f3
Create Date: 2023-05-02 16:40:45.958154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cc58aa691c'
down_revision = '6d5a126f64f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
